# Generated by Django 4.0.5 on 2022-06-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='intro',
        ),
    ]
