# Generated by Django 4.0.5 on 2022-06-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_posts_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title_image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
