# Generated by Django 4.0.5 on 2022-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posts_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.TextField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('business', 'Business'), ('history', 'History')], default='business', max_length=255),
        ),
    ]
