# Generated by Django 4.0.5 on 2022-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_posts_title_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.TextField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('business', 'Business'), ('history', 'History'), ('entertainment', 'Entertainment'), ('tech', 'Tech')], default='business', max_length=255),
        ),
    ]
