# Generated by Django 4.0.5 on 2022-07-18 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_category_alter_posts_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.TextField(choices=[('sports', 'sports'), ('tech', 'tech'), ('business', 'business'), ('history', 'history'), ('entertainment', 'entertainment'), ('politics', 'politics'), ('crime', 'crime'), ('Human Resources', 'Human Resources'), ('Human Res', 'Human Res'), ('Good News', 'Good News'), ('Bad News', 'Bad News'), ('Jumbo', 'Jumbo')], default='business', max_length=255),
        ),
    ]
