# Generated by Django 4.0.5 on 2022-07-20 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_member_posts_likes_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
