# Generated by Django 4.0.5 on 2022-07-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_posts_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y%m%d'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('profile_picture', models.ImageField(upload_to='images/profile/%y%m%d')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
