# Generated by Django 4.0.5 on 2022-09-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_posts_dislikes_posts_favourites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pintrest',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/%y%m%d'),
        ),
    ]
