# Generated by Django 4.0.5 on 2022-09-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
